# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true


gems: [jekyll-paginate]


# Setup

title:          "Tomato's Blog"
tagline:        "Quiet And Powerful"
description:    "Something Specail"
url:            "http://bl4ck.in"
baseurl:        ""
paginate:       20
paginate_path:  "/page:num"

# Custom vars
friends:
    - name: "Syclover"
      url: "http://blog.sycsec.com"
      desc: "三叶草安全小组"

author:
    name: "Tomato"
    email: "0xtom4to@gmail.com"
    weibo: "http://weibo.com/tomato4web"
    twitter: ""
    github: ""

disqus:
    shortname: ""
    show: False


markdown: kramdown
